spring.application.name=irctcApp
server.port=9091
spring.datasource.url=jdbc:mysql://localhost:3306/manidatabase
spring.datasource.username=root
spring.datasource.password=toor
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
